name = "changli"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

account_id = "ea1aab81dc8e22018131832d124a54fc"
workers_dev = true

routes = [
  { pattern = "blog.webex.com.xinquins.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.xinquins.dpdns.org", custom_domain = true },
  { pattern = "quiz.vidio.com.xinquins.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.xinquins.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.xinquins.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.xinquins.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.xinquins.dpdns.org", custom_domain = true },
  { pattern = "v.whatsapp.net.xinquins.dpdns.org", custom_domain = true },
  { pattern = "investor.fb.com.xinquins.dpdns.org", custom_domain = true },

[[kv_namespaces]]
binding = "YUMI"
id = "fde4b995806b4140878831efa48d43d8"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "aacac2d2-cac8-442a-9f2c-4e4f807065f5"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/ziyosen/Changli/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/ziyosen/Changli/refs/heads/main/web/sub.html"
